"""empty message

Revision ID: 77b6b2440f88
Revises: 88fe2a1ba793
Create Date: 2021-02-12 23:27:25.807089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b6b2440f88'
down_revision = '88fe2a1ba793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesas', sa.Column('situacao', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mesas', 'situacao')
    # ### end Alembic commands ###
