"""empty message

Revision ID: 88fe2a1ba793
Revises: 
Create Date: 2020-06-05 21:14:17.168412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88fe2a1ba793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administador',
    sa.Column('administrador_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('senha', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('administrador_id')
    )
    op.create_table('categorias',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nome_categoria', sa.String(length=100), nullable=True),
    sa.Column('data_postagem', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('categoria_id')
    )
    op.create_table('mesas',
    sa.Column('mesa_id', sa.Integer(), nullable=False),
    sa.Column('numero_mesa', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('mesa_id'),
    sa.UniqueConstraint('numero_mesa')
    )
    op.create_table('produtos',
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(), nullable=True),
    sa.Column('valor', sa.DECIMAL(), nullable=True),
    sa.Column('imagem', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('produto_id')
    )
    op.create_table('carrinho',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.mesa_id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.produto_id'], ),
    sa.PrimaryKeyConstraint('produto_id')
    )
    op.create_table('categoriasprodutos',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.categoria_id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.produto_id'], ),
    sa.PrimaryKeyConstraint('categoria_id', 'produto_id')
    )
    op.create_table('pedidos',
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('valor_total', sa.DECIMAL(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.mesa_id'], ),
    sa.PrimaryKeyConstraint('pedido_id')
    )
    op.create_table('pagamentos',
    sa.Column('pagamento_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('nome_pagamento', sa.String(length=50), nullable=True),
    sa.Column('montante', sa.DECIMAL(), nullable=True),
    sa.Column('resposta', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.pedido_id'], ),
    sa.PrimaryKeyConstraint('pagamento_id')
    )
    op.create_table('pedidossolicitados',
    sa.Column('pedidosolicitado_id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.pedido_id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.produto_id'], ),
    sa.PrimaryKeyConstraint('pedidosolicitado_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidossolicitados')
    op.drop_table('pagamentos')
    op.drop_table('pedidos')
    op.drop_table('categoriasprodutos')
    op.drop_table('carrinho')
    op.drop_table('produtos')
    op.drop_table('mesas')
    op.drop_table('categorias')
    op.drop_table('administador')
    # ### end Alembic commands ###
